require: rubocop-minitest

AllCops:
  TargetRubyVersion: 2.4
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Layout/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Naming/FileName:
  Enabled: false
Style/NumericPredicate:
  EnforcedStyle: comparison
