language: ruby
cache: bundler
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.4
  - 2.4.1
after_success:
  - bundle exec codeclimate-test-reporter
addons:
  code_climate:
    repo_token: 357da37cbdcc472b4b33ba5f6e8a6fcc14ebcb41bb951b5133c547818ad6fbb3
